/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

import BL.BLPlato;
import BL.BLRestaurante;
import Clases2.Plato;
import Clases2.Restaurante;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class Pantalla_Pedidos extends javax.swing.JFrame {
    ArrayList<Plato> ArrayKfc = new ArrayList<>();
    ArrayList<Restaurante> ArrayRestaurante = new ArrayList<>();
    ArrayList<Plato> ArrayPlatos;
    Restaurante objRest = new Restaurante();
    Plato objPlat = new Plato();
    BLPlato objBLplato = new BLPlato();
    BLRestaurante objBLrestaurante = new BLRestaurante();
    int selected = -1;
    /**
     * Creates new form Pantalla_Pedidos
     */
    public Pantalla_Pedidos() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        ArrayKfc = objBLplato.ConsultarPlatoDB();
       
//        ObtenerRestaurantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLISTAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonENVIARPED = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setText("ENVÍO DE PEDIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 970, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("ESCOJA EL RESTAURANTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonLISTAR.setText("LISTAR");
        jButtonLISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLISTARActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLISTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 90));

        jButtonENVIARPED.setText("ENVIAR");
        jPanel2.add(jButtonENVIARPED, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 480, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel3.setText("PLATOS DISPONIBLES");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 480, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLISTARActionPerformed
        // TODO add your handling code here:
        jTable1.removeAll();
        try {
            ArrayRestaurante = objBLrestaurante.ConsultarRestauranteDB();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object columnas[] = {"N°","CODIGO DEL RESTAURANTE","NOMBRE RESTAURANTE", "HORARIO ATENCION", "HORARIO HORAS"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
            for(Restaurante objRest : ArrayRestaurante){
                String NewValor[] = {Integer.toString(objRest.getIdRest()), 
                    objRest.getCodigoRest(),
                    objRest.getNombreRes(), 
                    objRest.getHorarioRes(),
                    objRest.getHorarioHoras()};
                modelo.addRow(NewValor);
            }
        
    }//GEN-LAST:event_jButtonLISTARActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        ArrayList<Plato> ArrayPlatos;
        selected = jTable1.getSelectedRow();
        jTable2.removeAll();
        Object columnas[] = {"NOMBRE PLATO/COMBO","PRECIO", "DETALLE"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable2.setModel(modelo);
        ArrayPlatos = ArrayRestaurante.get(selected).platos;
        for (Plato objPlat:ArrayPlatos ){
            String NewValor[] = {String.valueOf(objPlat.getIdPlat()),
                objPlat.getNombrePlato(),
                String.valueOf(objPlat.getPrecio()), 
                objPlat.getDetalle()       
            };
            modelo.addRow(NewValor);
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked
    
//    public void ObtenerRestaurantes(){
//        try {
//            BLRestaurante objBLRestaurante = new BLRestaurante();
//            ArrayList<Restaurante> listRestaurante = new ArrayList<>();
//            objBLRestaurante.ObtenerRestaurantes(listRestaurante);
//            DefaultComboBoxModel ModRestaurante = new DefaultComboBoxModel();
//            for (Restaurante r : listRestaurante){
//                ModRestaurante.addElement(r);
//                jComboBox1.setModel(ModRestaurante);
////                MostrarRestaurantes((Restaurante) jComboBox1.getSelectedItem());
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Pantalla_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    
//    public void MostrarRestaurantes(Restaurante objRest) {
//        ArrayList<Restaurante> listRestaurantes = new ArrayList<>();
//        listRestaurantes = objRest.getRestaurantes();
//        DefaultComboBoxModel ModRestaurantes = new DefaultComboBoxModel();
//        for (Restaurante c : listRestaurantes) {
//            ModRestaurantes.addElement(c);
//            jComboBox1.setModel(ModRestaurantes);
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pantalla_Pedidos().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Pantalla_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Pantalla_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonENVIARPED;
    private javax.swing.JButton jButtonLISTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
