/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

import BL.BLCliente;
import BL.BLUsuario;
import Clases2.Cliente;
import Clases2.Usuario;
import Logica.Expresiones;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class Pantalla_Registro_Cliente extends javax.swing.JFrame {
    BLCliente objBLcliente = new BLCliente();
    BLUsuario objBLusuario = new BLUsuario();

    /**
     * Creates new form Pantalla_Registro_Cliente
     */
    public Pantalla_Registro_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPRIMERNOMBRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSEGUNDONOMBRE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPRIMERAPELLIDO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSEGUNDOAPELLIDO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCEDULA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTARJETA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTELEFONO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDIRECCION = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCORREO = new javax.swing.JTextField();
        jButtonREVISAR = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCONTRASEÑA = new javax.swing.JTextField();
        jButtonREGISTRO = new javax.swing.JButton();
        jButtonATRAS = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE USUARIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("PRIMER NOMBRE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(jTextFieldPRIMERNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        jLabel3.setText("SEGUNDO NOMBRE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        jPanel2.add(jTextFieldSEGUNDONOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 210, -1));

        jLabel4.setText("PRIMER APELLIDO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel2.add(jTextFieldPRIMERAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, -1));

        jLabel5.setText("SEGUNDO APELLIDO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));
        jPanel2.add(jTextFieldSEGUNDOAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 210, -1));

        jLabel6.setText("CEDULA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel2.add(jTextFieldCEDULA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 240, -1));

        jLabel7.setText("N° TARJETA CRÉDITO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        jPanel2.add(jTextFieldTARJETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 210, -1));

        jLabel8.setText("TELÉFONO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel2.add(jTextFieldTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 220, -1));

        jLabel9.setText("DIRECCIÓN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel2.add(jTextFieldDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 630, -1));

        jLabel10.setText("CORREO ELECTRÓNICO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel2.add(jTextFieldCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 450, -1));

        jButtonREVISAR.setText("REVISAR");
        jButtonREVISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREVISARActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonREVISAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel11.setText("CONTRASEÑA");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel2.add(jTextFieldCONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 280, -1));

        jButtonREGISTRO.setText("REGISTRARSE");
        jButtonREGISTRO.setEnabled(false);
        jButtonREGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGISTROActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonREGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jButtonATRAS.setText("ATRÁS");
        jButtonATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRASActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jLabel12.setText("*Deben llenarse obligatoriamente cada uno de los campos requeridos*");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 750, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonREVISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREVISARActionPerformed
        // TODO add your handling code here:
        Expresiones comprobar = new Expresiones();
        Cliente objCli = new Cliente();
        if (this.jTextFieldPRIMERNOMBRE.getText().isEmpty()
                
                || this.jTextFieldSEGUNDONOMBRE.getText().isEmpty()
                || this.jTextFieldPRIMERAPELLIDO.getText().isEmpty() 
                || this.jTextFieldSEGUNDOAPELLIDO.getText().isEmpty()
                || this.jTextFieldCEDULA.getText().isEmpty()
                || this.jTextFieldTARJETA.getText().isEmpty()
                || this.jTextFieldTELEFONO.getText().isEmpty()
                || this.jTextFieldCORREO.getText().isEmpty()
               || (this.jTextFieldCONTRASEÑA.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "TIENE CAMPOS FALTANTES POR LLENAR");
        } else if (!comprobar.numeroCedula(this.jTextFieldCEDULA.getText())){
            JOptionPane.showMessageDialog(null, "CEDULA INVALIDA");
        }else if(!comprobar.numeroTarjeta(this.jTextFieldTARJETA.getText())){
            JOptionPane.showMessageDialog(null, "NUMERO DE TARJETA INVALIDO");
        }else if(!comprobar.numeroCelular(this.jTextFieldTELEFONO.getText())){
            JOptionPane.showMessageDialog(null, "NUMERO DE TELEFONO INVALIDO");
        }else if(!comprobar.mailValiodo(this.jTextFieldCORREO.getText())){
            JOptionPane.showMessageDialog(null, "CORREO ELECTRONICO INVALIDO");
        }else if(!comprobar.contrasenia(this.jTextFieldCONTRASEÑA.getText())){
            JOptionPane.showMessageDialog(null, "CONTRASEÑA INVALIDA");
        }else{     
            this.jButtonREGISTRO.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonREVISARActionPerformed

    private void jButtonREGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGISTROActionPerformed
        try {
            // TODO add your handling code here:
            Usuario objUsua = new Usuario();
            Cliente objClie = new Cliente(0, this.jTextFieldCEDULA.getText(), this.jTextFieldPRIMERAPELLIDO.getText(),
                    this.jTextFieldSEGUNDOAPELLIDO.getText(), this.jTextFieldPRIMERNOMBRE.getText(),
                    this.jTextFieldSEGUNDONOMBRE.getText(), this.jTextFieldTELEFONO.getText(),
                    this.jTextFieldDIRECCION.getText(), this.jTextFieldCORREO.getText(), this.jTextFieldCONTRASEÑA.getText());
            objBLcliente.InsertarClienteDB(objClie);
//            objUsua = new Usuario(0, this.jTextFieldCEDULA.getText(), this.jTextFieldCONTRASEÑA.getText());
            objClie.AgregarUsuario(0, this.jTextFieldCEDULA.getText(), this.jTextFieldCONTRASEÑA.getText());
           
            objBLusuario.InsertarUsuarioDB2(objClie);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonREGISTROActionPerformed

    private void jButtonATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRASActionPerformed
        // TODO add your handling code here:
        dispose();
        Pantalla_Principal c = new Pantalla_Principal();
        c.setVisible(true);
    }//GEN-LAST:event_jButtonATRASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonATRAS;
    private javax.swing.JButton jButtonREGISTRO;
    private javax.swing.JButton jButtonREVISAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCEDULA;
    private javax.swing.JTextField jTextFieldCONTRASEÑA;
    private javax.swing.JTextField jTextFieldCORREO;
    private javax.swing.JTextField jTextFieldDIRECCION;
    private javax.swing.JTextField jTextFieldPRIMERAPELLIDO;
    private javax.swing.JTextField jTextFieldPRIMERNOMBRE;
    private javax.swing.JTextField jTextFieldSEGUNDOAPELLIDO;
    private javax.swing.JTextField jTextFieldSEGUNDONOMBRE;
    private javax.swing.JTextField jTextFieldTARJETA;
    private javax.swing.JTextField jTextFieldTELEFONO;
    // End of variables declaration//GEN-END:variables
}
