/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AGUI;

import BL.BLPlato;
import BL.BLRestaurante;
import Clases2.Plato;
import Clases2.Restaurante;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jorge
 */
public class Pantalla_Registro_Platos extends javax.swing.JFrame {
    Restaurante objRest = new Restaurante();
    Plato objPlat = new Plato();
    BLRestaurante objBLrestaurante = new BLRestaurante(); 
    BLPlato objBLplato = new BLPlato(); 
    /**
     * Creates new form Pantalla_Registro_Platos
     */
    public Pantalla_Registro_Platos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCODIGOREST = new javax.swing.JTextField();
        jButtonBUSCAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNOMBREREST = new javax.swing.JTextField();
        jTextFieldDIAS = new javax.swing.JTextField();
        jTextFieldHORARIO = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNOMBREPLATO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPRECIO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDETALLE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE PLATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("SELECCIÓN DEL RESTAURANTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel3.setText("INGRESE CODIGO DEL RESTAURANTE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel2.add(jTextFieldCODIGOREST, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 170, -1));

        jButtonBUSCAR.setText("BUSCAR");
        jButtonBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBUSCARActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("DATOS DEL RESTAURANTE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel5.setText("NOMBRE RESTAURANTE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setText("DIAS ATENCIÓN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel7.setText("HORARIO ATENCIÓN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jTextFieldNOMBREREST.setEnabled(false);
        jPanel2.add(jTextFieldNOMBREREST, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));

        jTextFieldDIAS.setEnabled(false);
        jPanel2.add(jTextFieldDIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));

        jTextFieldHORARIO.setEnabled(false);
        jPanel2.add(jTextFieldHORARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 690, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel8.setText("INGRESO DE DATOS DEL NUEVO PLATO");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel9.setText("NOMBRE PLATO");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextFieldNOMBREPLATO.setEnabled(false);
        jPanel3.add(jTextFieldNOMBREPLATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 260, -1));

        jLabel10.setText("PRECIO");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTextFieldPRECIO.setEnabled(false);
        jPanel3.add(jTextFieldPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        jLabel11.setText("DETALLES DEL PLATO");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTextFieldDETALLE.setEnabled(false);
        jPanel3.add(jTextFieldDETALLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 290, 80));

        jButton1.setText("GUARDAR");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jButton2.setText("SALIR");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 690, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBUSCARActionPerformed
        try {
            // TODO add your handling code here:
            objRest = objBLrestaurante.ConsultarCodigoResDB(this.jTextFieldCODIGOREST.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jTextFieldNOMBREREST.setText(objRest.getNombreRes());
        this.jTextFieldDIAS.setText(objRest.getHorarioRes());
        this.jTextFieldHORARIO.setText(objRest.getHorarioHoras());
        this.jTextFieldNOMBREPLATO.setEnabled(true);
        this.jTextFieldPRECIO.setEnabled(true);
        this.jTextFieldDETALLE.setEnabled(true);
        this.jButton1.setEnabled(true);
    }//GEN-LAST:event_jButtonBUSCARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        objRest.AgregarPlato(0, this.jTextFieldNOMBREPLATO.getText(), Double.valueOf(this.jTextFieldPRECIO.getText())
                , this.jTextFieldDETALLE.getText());
        try {
            objBLplato.InsertarPlato(objRest);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Registro_Platos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Registro_Platos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBUSCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCODIGOREST;
    private javax.swing.JTextField jTextFieldDETALLE;
    private javax.swing.JTextField jTextFieldDIAS;
    private javax.swing.JTextField jTextFieldHORARIO;
    private javax.swing.JTextField jTextFieldNOMBREPLATO;
    private javax.swing.JTextField jTextFieldNOMBREREST;
    private javax.swing.JTextField jTextFieldPRECIO;
    // End of variables declaration//GEN-END:variables
}
